
ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

NAME=wdtkick
LDFLAGS+= $(DEBUG) $(TARGET) -lsecpol

define PINFO
PINFO DESCRIPTION = Watchdog Driver
endef

USEFILE=$(PROJECT_ROOT)/wdtkick.use


#This has to be included last

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk
