# App Ethercat Slave
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcTaskEthercatSlaveBase
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcTaskEthercatSlaveServoBase
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlaveBase
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcCia402
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlave/EcSlaveEl1008
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlave/EcSlaveEl2008
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlave/EcSlaveEl3024
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlave/EcSlaveEl6002
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlave/EcSlaveRfidslave
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlave/EcSlaveSscIoModule
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlave/EcSlaveEncbrkctrl
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlave/EcSlavePitchDrive
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlave/EcSlaveDenNetE
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlave/EcSlaveElmoDrive
INCLUDES += -I$(DIR_APP_ETHERCAT_SLAVE)/EcSlave/EcSlaveIpos2401MxCat

# App FSM
INCLUDES += -I$(DIR_APP_FSM)/EcState
INCLUDES += -I$(DIR_APP_FSM)/EcStateClearingFault
INCLUDES += -I$(DIR_APP_FSM)/EcStateDisabled
INCLUDES += -I$(DIR_APP_FSM)/EcStateDisabling
INCLUDES += -I$(DIR_APP_FSM)/EcStateEnabled
INCLUDES += -I$(DIR_APP_FSM)/EcStateEnabling
INCLUDES += -I$(DIR_APP_FSM)/EcStateFault
INCLUDES += -I$(DIR_APP_FSM)/EcStateInitialized
INCLUDES += -I$(DIR_APP_FSM)/EcStateInitializing
INCLUDES += -I$(DIR_APP_FSM)/EcStateJoystickControl
INCLUDES += -I$(DIR_APP_FSM)/EcStateReady
INCLUDES += -I$(DIR_APP_FSM)/EcStateStandby

# App User
INCLUDES += -I$(DIR_APP_USER)/EcTaskUserBase
INCLUDES += -I$(DIR_APP_USER)/EcUser_1
INCLUDES += -I$(DIR_APP_USER)/EcUser_2
INCLUDES += -I$(DIR_APP_USER)/EcUser_3

# App Robot Control
INCLUDES += -I$(DIR_APP_ROBOT_CONTROL)/EcTaskRobotControlBase

# App Interface
INCLUDES += -I$(DIR_APP_INTERFACE)/EcTaskInterfaceBase
