
ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

NAME=ecm-mec170x
LIBS += secpol
LDFLAGS+=-Wl,--no-undefined

define PINFO
PINFO DESCRIPTION=ECM mec170x resmgr
endef
#This has to be included last
USEFILE=$(PROJECT_ROOT)/$(NAME).use

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

-include $(PROJECT_ROOT)/roots.mk